---
title: "Social and Cultural Dynamics"
author: "Alberte Baggesgaard Seeberg"
date: "2/5/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
#Setting working directory
setwd("~/Desktop/Exam SocCult/SocCultExam")
devtools::install_github("rmcelreath/rethinking", force = TRUE)
library(dplyr)
library(tidyverse)
library(rethinking)
library(ggplot2)
library(cowplot)


Ultimatum <- do.call("rbind", lapply( list.files("~/Desktop/Exam SocCult/SocCultExam/Ultimatum",full=TRUE),
		read.csv, header=TRUE))

UG3=read.csv("ultimatumS3_p.csv", sep=";")
UG11=read.csv("ultimatum11.csv", sep=";")

Ultimatum=rbind(Ultimatum, UG3)
Ultimatum=rbind(Ultimatum, UG11)

Survey <- do.call("rbind", lapply( list.files("~/Desktop/Exam SocCult/SocCultExam/Survey",full=TRUE),
		read.csv, header=TRUE))

PublicGoods <- do.call("rbind", lapply( list.files("~/Desktop/Exam SocCult/SocCultExam/Public_Goods",full=TRUE),
		read.csv, header=TRUE))

PG4=read.csv("public_goodsS4_p.csv", sep=";")
PG5=read.csv("public_goodsS5_u.csv", sep=";")

PublicGoods=rbind(PublicGoods, PG4)

PublicGoods=rbind(PublicGoods, PG5)

Winners=data.frame(Ultimatum$participant.code, Ultimatum$player.team)

Winners$participant.code=Winners$Ultimatum.participant.code
Winners$team=Winners$Ultimatum.player.team

Winners=Winners[-2]
Winners=Winners[-1]

Winners=Winners[!duplicated(Winners$participant.code),]


PG_R1=subset(PublicGoods[PublicGoods$subsession.round_number=="1",])
PG_R2=subset(PublicGoods[PublicGoods$subsession.round_number=="2",])

PG1=merge(PG_R1, Winners, by="participant.code")
PG2=merge(PG_R2, Winners, by="participant.code")

PG1=PG1[,c(1,2,15,16,17,20,22,23,26,33)]
PG2=PG2[,c(1,2,15,16,17,20,22,23,26,33)]

PG1$round=1
PG2$round=2

alldata=rbind(PG1,PG2)


```


```{r}
#Finding mean contribution from winners and loosers 
mean(alldata$player.contribution[alldata$team=="1"])
mean(alldata$player.contribution[alldata$team=="2"])

#Density plot for contributions of winners and loosers including HPDI
plot6 = dens(alldata$player.contribution[alldata$team=="1"], xlim=c(0,100) , xlab="Contribution", show.HPDI=0.50, col="red")

plot5 = dens(alldata$player.contribution[alldata$team=="2"], xlim=c(0,100) , xlab="Contribution", show.HPDI=0.50, add=TRUE)

#Calculating HPDI
HPDI(alldata$player.contribution[alldata$team=="1"], prob=0.50)
HPDI(alldata$player.contribution[alldata$team=="2"], prob=0.50)

#Intercept only model
model1=map(
alist(
player.contribution ~ dnorm( mu , sigma ),
mu <- Interceptall+Intercept[session.code],
Interceptall ~ dnorm(50,20),
Intercept[session.code] ~ dnorm(0,10),
sigma ~ dunif(0,50)
),
data=alldata)


precis1=precis(model1)

precis1
plot(precis1)

#Model with teams as predictive variable
model2=map(
alist(
player.contribution ~ dnorm( mu , sigma ),
mu <- Interceptall+Intercept[session.code] +
(b_teamall+b_team[session.code])*team,
Interceptall ~ dnorm(50,20),
b_teamall ~ dnorm(0,10),
Intercept[session.code] ~ dnorm(0,10),
b_team[session.code] ~ dnorm(0,10),
sigma ~ dunif(0,50)
),
data=alldata)


precis2=precis(model2)

precis2
plot(precis2)

#simulating how new data might look like from samples from our data
x=extract.samples(model2)

sum(x$b_teamall<0)/10000
#0.79

#Model with interaction effect between teams and rounds
model3=map(
alist(
player.contribution ~ dnorm( mu , sigma ),
mu <- Interceptall+Intercept[session.code] +
(b_teamall+b_team[session.code])*team+
(b_roundall+b_round[session.code])*round+
(b_interactionall+b_interaction[session.code])*round*team,
Interceptall ~ dnorm(50,20),
b_teamall ~ dnorm(0,10),
Intercept[session.code] ~ dnorm(0,10),
b_team[session.code] ~ dnorm(0,10),
b_interactionall~dnorm(0,5),
b_interaction[session.code]~dnorm(0,5),
b_roundall~dnorm(0,10),
b_round[session.code]~dnorm(0,10),
sigma ~ dunif(0,50)
),
data=alldata)

precis3=precis(model3)
precis3

plot(precis3)




#Comparing models 1, 2, and 3

beta1 <- coeftab(model1, model2, model3)
pars1 <- c("Interceptall", "b_teamall", "b_roundall", "b_interactionall", "sigma")
coeftab_plot(beta1, NULL , pars1, col.ci="rosybrown4", by.model=FALSE , prob=0.89)

models=compare(model1, model2, model3)
models
plot(models)


#Observed vs predicted contributions model 1
mu <- link( model1)
# calculating mean and HPDI for each data point
mu.mean <- apply( mu , 2 , mean )
mu.HPDI <- apply( mu , 2 , HPDI )
# simulate observations
cont.sim <- sim( model1 , n=1e4 )
cont.HPDI <- apply( cont.sim , 2 , HPDI )

#plotting
plot( mu.mean ~ alldata$player.contribution , col=rangi2 , ylim=range(mu.HPDI) ,
xlab="Observed contribution" , ylab="Predicted contribution" )
abline( a=0 , b=1 , lty=2 )
for ( i in 1:nrow(alldata) )
lines( rep(alldata$player.contribution[i],2) , c(mu.HPDI[1,i],mu.HPDI[2,i]) ,
col=rangi2 )

#Observed vs predicted contributions model 2
mu <- link( model2)
# calculating mean and HPDI for each data point
mu.mean <- apply( mu , 2 , mean )
mu.HPDI <- apply( mu , 2 , HPDI )
# simulate observations
cont.sim <- sim( model2 , n=1e4 )
cont.HPDI <- apply( cont.sim , 2 , HPDI )

#plotting
plot( mu.mean ~ alldata$player.contribution , col=rangi2 , ylim=range(mu.HPDI) ,
xlab="Observed contribution" , ylab="Predicted contribution" )
abline( a=0 , b=1 , lty=2 )
for ( i in 1:nrow(alldata) )
lines( rep(alldata$player.contribution[i],2) , c(mu.HPDI[1,i],mu.HPDI[2,i]) ,
col=rangi2 )


# #Density plots for round 1, including HPDI
# plot2 = dens(PG1$player.contribution[PG1$team=="2"], xlim=c(0,100) , xlab="Contribution", show.HPDI=0.50, col="red")
# 
# plot1 = dens(PG1$player.contribution[PG1$team=="1"], xlim=c(0,100) , xlab="Contribution", show.HPDI=0.50, add=TRUE)
# 
# #Density plots for round 2, including HPDI
# plot3 = dens(PG2$player.contribution[PG2$team=="2"], xlim=c(0,100) , xlab="Contribution", show.HPDI=0.50, col="red")
# 
# plot4 = dens(PG2$player.contribution[PG2$team=="1"], xlim=c(0,100) , xlab="Contribution", show.HPDI=0.50, add=TRUE)
# 




```


